/**
 * This file was generated by the JPA Modeler
 */
package entity;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;

/**
 * @author user
 */
@Entity
public class Notification implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Basic
    private String message;

    @Basic
    private boolean estLu;

    @Basic
    @Temporal(TemporalType.DATE)
    private Date dateNotif;


    @ManyToOne(targetEntity = Utilisateur.class)
    @OnDelete(action = OnDeleteAction.CASCADE)
    private Utilisateur emetteur;

    @ManyToOne(targetEntity = Utilisateur.class)
    @OnDelete(action = OnDeleteAction.CASCADE)
    private Utilisateur recepteur;

    @ManyToOne(targetEntity = Service.class)
    @OnDelete(action = OnDeleteAction.CASCADE)
    private Service service;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public boolean isEstLu() {
        return this.estLu;
    }

    public void setEstLu(boolean estLu) {
        this.estLu = estLu;
    }

    public Date getDateNotif() {
        return this.dateNotif;
    }

    public void setDateNotif(Date dateNotif) {
        this.dateNotif = dateNotif;
    }

    public Utilisateur getEmetteur() {
        return this.emetteur;
    }

    public void setEmetteur(Utilisateur emetteur) {
        this.emetteur = emetteur;
    }

    public Utilisateur getRecepteur() {
        return this.recepteur;
    }

    public void setRecepteur(Utilisateur recepteur) {
        this.recepteur = recepteur;
    }

    public Service getService() {
        return this.service;
    }

    public void setService(Service service) {
        this.service = service;
    }

}
