/**
 * This file was generated by the JPA Modeler
 */
package entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;

/**
 * @author user
 */
@Entity
public class Service implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Basic
    private String typeService;

    @Basic
    @Temporal(TemporalType.DATE)
    private Date dateDebut;

    @Basic
    @Temporal(TemporalType.DATE)
    private Date dateFin;

    @Basic
    private String courteDescription;

    @Basic
    private String longueDescription;

    @Basic
    private String localisation;

    @Basic
    private String etat;

    @Basic
    private String offreService;

    @OneToOne(targetEntity = NatureService.class)
    private NatureService natureService;

    @ManyToOne(targetEntity = Utilisateur.class)
    @OnDelete(action = OnDeleteAction.CASCADE)
    private Utilisateur demandeUser;

    @ManyToOne(targetEntity = Utilisateur.class)
    @OnDelete(action = OnDeleteAction.CASCADE)
    private Utilisateur offreUser;

    @OneToMany(targetEntity = Notification.class, mappedBy = "service", cascade = CascadeType.REMOVE)
    private List<Notification> notifications;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTypeService() {
        return this.typeService;
    }

    public void setTypeService(String typeService) {
        this.typeService = typeService;
    }

    public Date getDateDebut() {
        return this.dateDebut;
    }

    public void setDateDebut(Date dateDebut) {
        this.dateDebut = dateDebut;
    }

    public Date getDateFin() {
        return this.dateFin;
    }

    public void setDateFin(Date dateFin) {
        this.dateFin = dateFin;
    }

    public String getCourteDescription() {
        return this.courteDescription;
    }

    public void setCourteDescription(String courteDescription) {
        this.courteDescription = courteDescription;
    }

    public String getLongueDescription() {
        return this.longueDescription;
    }

    public void setLongueDescription(String longueDescription) {
        this.longueDescription = longueDescription;
    }

    public String getLocalisation() {
        return this.localisation;
    }

    public void setLocalisation(String localisation) {
        this.localisation = localisation;
    }

    public String getEtat() {
        return this.etat;
    }

    public void setEtat(String etat) {
        this.etat = etat;
    }

    public String getOffreService() {
        return this.offreService;
    }

    public void setOffreService(String offreService) {
        this.offreService = offreService;
    }

    public NatureService getNatureService() {
        return this.natureService;
    }

    public void setNatureService(NatureService natureService) {
        this.natureService = natureService;
    }

    public Utilisateur getDemandeUser() {
        return this.demandeUser;
    }

    public void setDemandeUser(Utilisateur demandeUser) {
        this.demandeUser = demandeUser;
    }

    public Utilisateur getOffreUser() {
        return this.offreUser;
    }

    public void setOffreUser(Utilisateur offreUser) {
        this.offreUser = offreUser;
    }

    public List<Notification> getNotifications() {
        return this.notifications;
    }

    public void setNotifications(List<Notification> notifications) {
        this.notifications = notifications;
    }

}
