/**
 * This file was generated by the JPA Modeler
 */
package entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * @author user
 */
@Entity
public class Utilisateur implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long codeUtilisateur;

    @Basic
    private String nom;

    @Basic
    private String prenom;

    @Basic
    private String login;

    @Basic
    private String mdp;

    @Basic
    private String email;

    @Basic
    private String adresse;

    @Basic
    private String tel;

    @Basic
    private String description;

    @Basic
    private boolean estAdmin;

    @Basic
    @Temporal(TemporalType.DATE)
    private Date dateNaissance;

    @Basic
    private String sexe;

    @OneToMany(targetEntity = Service.class, mappedBy = "demandeUser", cascade = CascadeType.REMOVE)
    private List<Service> demandes;

    @OneToMany(targetEntity = Service.class, mappedBy = "offreUser", cascade = CascadeType.REMOVE)
    private List<Service> offres;

    @OneToMany(targetEntity = Notification.class, mappedBy = "recepteur", cascade = CascadeType.REMOVE)
    private List<Notification> notifcationRecep;

    public Long getCodeUtilisateur() {
        return this.codeUtilisateur;
    }

    public void setCodeUtilisateur(Long codeUtilisateur) {
        this.codeUtilisateur = codeUtilisateur;
    }

    public String getNom() {
        return this.nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public String getPrenom() {
        return this.prenom;
    }

    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getMdp() {
        return this.mdp;
    }

    public void setMdp(String mdp) {
        this.mdp = mdp;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getAdresse() {
        return this.adresse;
    }

    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    public String getTel() {
        return this.tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public boolean isEstAdmin() {
        return this.estAdmin;
    }

    public void setEstAdmin(boolean estAdmin) {
        this.estAdmin = estAdmin;
    }

    public Date getDateNaissance() {
        return this.dateNaissance;
    }

    public void setDateNaissance(Date dateNaissance) {
        this.dateNaissance = dateNaissance;
    }

    public String getSexe() {
        return this.sexe;
    }

    public void setSexe(String sexe) {
        this.sexe = sexe;
    }

    public List<Service> getDemandes() {
        return this.demandes;
    }

    public void setDemandes(List<Service> demandes) {
        this.demandes = demandes;
    }

    public List<Service> getOffres() {
        return this.offres;
    }

    public void setOffres(List<Service> offres) {
        this.offres = offres;
    }

    public List<Notification> getNotifcationRecep() {
        return this.notifcationRecep;
    }

    public void setNotifcationRecep(List<Notification> notifcationRecep) {
        this.notifcationRecep = notifcationRecep;
    }

}
